version: "3"

services:

  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - test-nfs:/usr/share/nginx/html/
    deploy:
      replicas: 3

    healthcheck:
      test: curl --fail http://localhost || exit 1
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 10s

volumes:
  nginx:
    driver: local
  test-nfs:
    driver_opts:
      type: "nfs"
      o: "addr=10.15.25.53,nolock,soft,rw"
      device: ":/mnt/docker/nfs
      