version: "3"

services:

  nginx:
    image: nginx:alpine
    ports:
      - 3000:80
    environment:
      - HELLO="Docker"
    volumes:
#      - testnfs:/mnt/docker/test
#      - type: bind
      - /mnt/docker/test/index.html:/usr/share/nginx/html/index.html
    deploy:
#      placement:
#        constraints: [node.role == manager]
      replicas: 1
